name: Stagg Designs
favicon: null
layout_spectrum: 0.7090944205410779
typography_spectrum: 0.3372597354464233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7625071241054684
  lightness: 0.20076682115904987
  saturation: 0.6980403868947178
  rhythmicContrast: 0.13193774945102632
purpose: []
